In [ ]:
import numpy as np

##The Basics (apparently)

In [ ]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [ ]:
b = np.array([[1.2, 2.4, 7.2], [1.2, 5.3, 3.2]])
b


array([[1.2, 2.4, 7.2],
       [1.2, 5.3, 3.2]])

In [ ]:
#Get Dimention
b.ndim

2

In [ ]:
#get shape
b.shape   #-> 2 rows, 3 cols

(2, 3)

In [ ]:
#Get Type
a.dtype

dtype('int64')

In [ ]:
a.itemsize

8

In [ ]:
#Get total size
a.size * a.itemsize
a.nbytes

24

## Accessing and changing specific elements, row, columns, etc..

In [ ]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
#get a specific element [r,c]
a[1, 5]

np.int64(13)

In [ ]:
#Get a specific row
a[0 , :]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
#Get a specific column
a[:,2]

array([ 3, 10])

In [ ]:
#getting for fancy -> [startindex:stopindex:stepsize]
print(a[:, 1:6:2])

[[ 2  4  6]
 [ 9 11 13]]


In [ ]:
#changin value
a
a[0,4] = 1
a
#changing row
a[:,5] = 3
a

array([[ 1,  2,  3,  4,  1,  3,  7],
       [ 8,  9, 10, 11, 12,  3, 14]])

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [ ]:
np.full(a.shape,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [ ]:
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [ ]:
np.full_like(a.shape, 4)

array([4, 4])

In [ ]:
#random decimals
np.random.rand(4,2)

array([[0.88300724, 0.75223532],
       [0.1522885 , 0.18849773],
       [0.38552958, 0.19868696],
       [0.34343933, 0.22249704]])

In [ ]:
#random integers
np.random.randint(10,size=(1,3))

array([[6, 8, 1]])

In [ ]:
#identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
arr = np.array([[1,2,3]])
np.repeat(arr, 3, axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])